### ISSUE TITLE
Configuration::compute_* is not invoked if RoleGroup object doesn't define `config` field

### ISSUE THREAD

**Issue by teozkr** [stackabletech/operator-rs#281]
This means that the following object works:

```yaml
apiVersion: imaginary.stackable.tech/v1alpha1
kind: ImaginaryCluster
metadata:
  name: imaginary-cluster
spec:
  role:
    roleGroup:
      config: {}
```

But the following might be missing crucial default values:

```yaml
apiVersion: imaginary.stackable.tech/v1alpha1
kind: ImaginaryCluster
metadata:
  name: imaginary-cluster
spec:
  role:
    roleGroup: {}
```
