### ISSUE TITLE
User defined role overrides are ignored by compute_files() 

### ISSUE THREAD

**Issue by razvan** [stackabletech/operator-rs#339]
## Description

Given a fictional CRD with role level configuration overrides like this:
```
brokers:
  configOverrides:
    server.properties:
      auto.create.topics.enable: "false"
  roleGroups:
    default:
      replicas: 1
```

and an implementation of `Configuration::compute_files()` that sets `auto.create.topics.enable` to `true`,
then the user defined override is ignored and the value of the property will be `true`.

Note that this doesn't happen with configuration overrides at group level!

The expectation of overrides is, that whatever the user has set , wins over everything else.
