### ISSUE TITLE
Make configuration of emptyDir or pvcs as storage resources simpler 

### ISSUE THREAD

**Issue by razvan** [stackabletech/operator-rs#497]
# Description

Make it possible to define storage resource manifests as:

```
            storage:
              segmentCache: # Enum called e.g. "StorageVolumeConfig" (new)
                emptyDir: # struct EmptyDirConfig (new)
                  capacity: 10Gi
                  medium: "" # or "Memory"
                # OR
                pvc: # PvcConfig struct
                  capacity: 10Gi
                  storageClass: "ssd"
                freePercentage: 5 # default: 5
```

Blocks: https://github.com/stackabletech/druid-operator/issues/306
