### ISSUE TITLE
Cannot change tcp liveness probes with pod overrides

### ISSUE THREAD

**Issue by razvan** [stackabletech/operator-rs#747]
### Affected version

0.0.0-dev

### Current and expected behavior

1. When using an integer as as port property:

```
....
      automatic-log-config:
        podOverrides:
          spec:
            containers:
              - name: airflow
                livenessProbe:
                  tcpSocket:
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  failureThreshold: 6
```

An error is raised complaining that the property must be a string:

```
    case.go:366: AirflowCluster.airflow.stackable.tech "airflow" is invalid: [spec.webservers.roleGroups.automatic-log-config.podOverrides.spec.containers[0].livenessProbe.tcpSocket.port: Invalid value: "integer": spec.webservers.roleGroups.automatic-log-config.podOverrides.spec.containers[0].livenessProbe.tcpSocket.port in body must be of type string: "integer", spec.webservers.roleGroups.custom-log-config.podOverrides.spec.containers[0].livenessProbe.tcpSocket.port: Invalid value: "integer": spec.webservers.roleGroups.custom-log-config.podOverrides.spec.containers[0].livenessProbe.tcpSocket.port in body must be of type string: "integer"]
```

2. When using a string as the `tcpSocket.port` property, the value must contain the name of the port and not the port number. So `"http"` and not `"8080"`

### Possible solution

Maybe use  `k8s-openapi 0.21.1` to pull in https://github.com/Arnavion/k8s-openapi/pull/153

### Additional context

It is apparently a known bug: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#intorstring

### Would you like to work on fixing this bug?

maybe

**Comment by sbernauer** [comment]
Now works like a charm (tested using 0.0.0-dev) and
```yaml
kind: HbaseCluster
spec:
  restServers:
    roleGroups:
      default:
        replicas: 1
        podOverrides:
          spec:
            containers:
              - name: hbase
                livenessProbe:
                  tcpSocket:
                    port: 1234
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  failureThreshold: 5
```
